{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "aspnet-sample-app.labels.stakater" . | indent 4 }}
{{ include "aspnet-sample-app.labels.chart" . | indent 4 }}
  name: {{ template "aspnet-sample-app.name" . }}
data:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}